USE MAPPS;
GO
CREATE MASTER KEY ENCRYPTION BY PASSWORD = '23987hxJ#KL95234nl0zBe'; GO

USE MAPPS;
--If there is no master key, create one now. 
IF NOT EXISTS 
    (SELECT * FROM sys.symmetric_keys WHERE symmetric_key_id = 101)
    CREATE MASTER KEY ENCRYPTION BY 
    PASSWORD = '23987hxJ#KL95234nl0zBe'
GO

CREATE CERTIFICATE SSN09
   WITH SUBJECT = 'Social Security Numbers'; GO

CREATE SYMMETRIC KEY SSN_Key11
    WITH ALGORITHM = AES_256
    ENCRYPTION BY CERTIFICATE SSN09;
GO